# Travis config for jdherman/SALib
language: python
matrix:
    - python: "2.7"
    - python: "3.3"
    env:
     - DEPS="numpy-1.6.0 scipy scikit-learn"
     - DEPS="numpy-1.7.0 scipy scikit-learn"
     - DEPS="numpy-1.8.0 scipy scikit-learn"
     - DEPS="numpy-1.9.1 scipy scikit-learn"

before_install:
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget http://repo.continuum.io/miniconda/Miniconda-3.4.2-Linux-x86_64.sh -O miniconda.sh;
    else
      wget http://repo.continuum.io/miniconda/Miniconda3-3.4.2-Linux-x86_64.sh -O miniconda.sh;
    fi
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/anaconda/bin:$PATH
  - conda update --yes conda

install:
  - conda create -n testenv --yes $DEPS pip python=$TRAVIS_PYTHON_VERSION
  - source activate testenv
  - python setup.py install
  - pip install coveralls
script:
  - coverage run --source=SALib setup.py test
after_success:
  - coveralls
notifications:
  email: false
