language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "pypy"
# command to install dependencies
virtualenv:
  system_site_packages: true
before_install:
  - sudo apt-get install python-numpy python-scipy 
  - pip install scikit-learn
# command to run tests
script: nosetests test --verbose
