name: SALib
channels:
  - conda-forge
dependencies:
  # required
  - numpy>=1.20.3
  - python>=3.8
  - pandas>=1.1.2
  - matplotlib>=3.2.2
  - scipy>=1.7.3
  - pathos>=0.2.5
  - numpydoc
  - pip
  - pip:
    - myst_parser
