name: SALib
channels:
  - conda-forge
dependencies:
  - python  # no pin for CI
  # required
  - numpy>=1.20.3
  - pandas>=2.0
  - matplotlib>=3.5
  - scipy>=1.9.3
  - pathos>=0.3.2
  # tests
  - pytest
  - pytest-cov
  # dev
  - pre-commit
  - hatch
  # doc
  - sphinx
  - numpydoc
  - pydata-sphinx-theme>=0.15.2
  - pip
  - pip:
    - myst_parser
